#64 company auth
kookmin-sw/capstone-2024-17 pull request #121
Opened 2024-04-28 09:33 UTC by jm3789

## #️⃣연관된 이슈

> #64

## 📝작업 내용

> 회사 인증 UI + 기능

### 스크린샷 (선택)

![collage](https://github.com/kookmin-sw/capstone-2024-17/assets/84127399/af4469a2-f128-4ca1-952e-24b1f5ee466b)

## 💬리뷰 요구사항(선택)

> /email/verification에 GET -> POST 로 변경
> s3 image url은 Image.network()로 Image 형태로 변경 가능

2024-04-28 11:02 UTC, chaeyeonKong commented on frontend/pubspec.lock
여기에 있는 sha256은 공개되어도 상관없는 값들인거죠?
pubspec.lock 파일도 ignore에 올려야하나 싶어서 물어봅니당

2024-04-28 11:51 UTC, jm3789 commented on frontend/pubspec.lock
넹 검색해보니 패키지 파일이 변경되었는지 식별하기 위한 해시값이라고 하네요! ignore에 넣지 않아도 될 거 같아용

2024-04-28 12:00 UTC, chaeyeonKong approved these changes

2024-04-29 10:52 UTC, godeka approved these changes
수고해쑝~~

2024-04-30 12:30 UTC, haram8009 requested changes

2024-04-30 12:30 UTC, haram8009 commented on frontend/lib/screen/search_company_screen.dart
> +  ];
domain 필드 추가 필요!

2024-04-30 12:57 UTC, jm3789 commented on frontend/lib/screen/search_company_screen.dart
> +  ];
api 응답에 domain 필드가 없씀...

2024-05-03 03:08 UTC, jm3789 commented
domain 추가 반영해따 !

2024-05-03 03:13 UTC, haram8009 approved these changes

2024-05-03 03:27 UTC, merged